version: "3.8"

services:
  auth-service:
   build: 
    context: .
    dockerfile: Dockerfile
    target: development
   command: pnpm run start:dev
   ports:
     - '3000:3000'
   volumes:
     - .:/usr/src/app
   env_file:
     - .env
   depends_on:
     - mysql_db
   networks:
    - mfa-network
  
  
  mysql_db:
    image: mysql
    ports:
      - '3308:3306'
    volumes:
      - mysql_data:/data/db
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_PASSWORD: ${MYSQL_DB_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE_NAME}
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
    networks:
      - mfa-network

volumes:
  mysql_data:
    
networks:
  mfa-network:
  